server:
  port: 8181

spring:
  application:
    name: Melodicle
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: postgres
#  datasource:
#    url: jdbc:h2:~/test2
#    platform: h2
#    username: sa
#    driver-class-name: org.h2.Driver
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#      settings:
#        web-allow-others: false
  jpa:
    database: POSTGRESQL
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update    #TODO: Change This for PROD.
    defer-datasource-initialization: true
  sql:
    init:
      mode: never

memms:
  app:
    jwtSecret: 413f848e4abc1aa9b79bc4259243377446481c4a74775874569bc7973f9d8c672275334c76a11e0f557a9b59b9fe8b79a08e65f4e0d6c214854c71e6122ac055
    jwtExpirationMs: 86400000 #24 hours

#springdoc:
#  paths-to-match:
#    - /api/**



