server:
  port: 8181

spring:
  application:
    name: Melodicle
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: postgres
#  datasource:
#    url: jdbc:h2:~/test2
#    platform: h2
#    username: sa
#    driver-class-name: org.h2.Driver
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#      settings:
#        web-allow-others: false
  jpa:
    database: POSTGRESQL
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop    #TODO: Change This for PROD.
    defer-datasource-initialization: true

#springdoc:
#  paths-to-match:
#    - /api/**



